### ISSUE TITLE
About the timer

### ISSUE THREAD

**Issue by iebox** [MTminded/JBGrammarTest#3]
- make the last 10% mins (2 mins) blinking in red or any other way to reminder user hurry up.
- extract the duration in index.php just like the db and domain name or something, 'cause we'll be change this a lot. 
  
  > say if too many student could finish this with in time, we'll shrink the timeline. 
- Now let's set this timeline to 10min instead of 15min for now.

**Comment by MTminded** [comment]
> extract the duration in index.php just like the db and domain name or something, 'cause we'll be change this a lot. 

@iebox Does this mean to store how long the student took to complete the test?

**Comment by iebox** [comment]
Nope. we don't store how long it takes.
We'll know wether the time is too much left for students by checking how many questions left as blank.

**Comment by MTminded** [comment]
Ok so by extract the duration in index.php, do you mean that the time limit is stored in the db?

**Comment by iebox** [comment]
well done! close this one!
